### ISSUE TITLE
Support rsp files in make

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/kbuild-os2#4] opened 2020-04-05 14:27 UTC
As sometimes the cmdline length gets bigger than 32k we should support rsp files. @komh die already a implementation fore make years ago. We should do it similar id say. Here is the reference https://github.com/komh/make-os2/commit/dc6f563bebe169d42b9be20c073df4d02da7cca9

**Comment by SilvanScherrer** [comment] 2020-04-05 14:28
It was found while working on gnutls. See https://github.com/bitwiseworks/gnutls-os2/issues/1

**Comment by dmik** [comment] 2023-01-13 10:28
I need this too to build NodeJS. Paul Smedley overcame it by using a newer make 4.x that has `$(file)` function which can directly write from variables to response files but I recall we had some issues with make 4 based kmk and decided to stay at make 3.81 base.

This feature seems useful regardless, so I will try to back port it.

Another option is just to back port `$(file)` function from make 4 which should also be easy.

**Comment by dmik** [comment] 2023-01-31 00:42
With the update of kBuild to the latest version, we now have `$(file)` but I still don't like this solution. At least, because it requires altering makefile logic for that. Another reason is because kLIBC (LIBCn) actually provides a much nicer solution for this problem which will work in most real life cases with make: if kLIBC `spawnvpe` detects that it's about to run a LIBC executable, it will not pass its arguments via a normal `DosExecPgm` mechanism; it will instead use shared memory to do so (it does a lot of special handling for the child process anyway, mainly regarding fork simulation, and passing command line is just one of them). Since most executables make starts are from our GNU toolchain that we build with kLIBC since long ago, this special handling gets involved for them. 

The problem is, however, that this special handling doesn't seem to always work when building NodeJS. I.e. for one library I get it working right, but then for the next one I suddenly get:
```
make: spawnvpe: environment space might be exhausted
make: execvp: C:/usr/bin/sh.exe: Invalid argument
make: fork: Invalid argument
```

I can't fully figure out why it happens yet; it needs more debugging.

**Comment by komh** [comment] 2023-01-31 10:46
Hi/2.

kLIBC does not pass arguments with shared memory to the child program which is the kLIBC executable. It will just change an argument style. As a result, without a rsp file, kLIBC cannot pass a very long command-line.

You can test with https://github.com/komh/os2compat/blob/master/testcase/spawnvpe-1.c and https://github.com/komh/os2compat/blob/master/testcase/spawnvpe-1-child.c.

You can build simply like:
```
gcc -o spawnvpe-1.exe spawnvpe-1.c
gcc -o spawnvpe-1-child.exe spawnvpe-1-child.c
```

Then, launch ```spawnvpe-1.exe```.

Anyway, if arguments and environment strings are passed with shared memory, it would be better.

Finally, the above error messages may come when passing very large environment strings over 32KiB.

**Comment by dmik** [comment] 2023-01-31 10:54
I'm currently looking at kLIBC to figure out what exactly is done there (as I may have forgot all the details) but if it's not there then I will simply implement it. Because I somehow dislike both the solution with @rsp files from your patch to make and Paul Smedley's `$(file)` workaround. Doing it on kLIBC level looks nicer to me (and will allow many cases to benefit because make is not the only one where we hit this command line length limit).

**Comment by komh** [comment] 2023-01-31 10:59
Absolutely agree. 

And do not forget to implement to pass environment strings as well as arguments, please...

**Comment by dmik** [comment] 2023-03-24 19:13
The above solution is done within the above LIBC ticket, closing this in favour of it. I've tested it and it works great. Once a new LIBCn is released, it will just work, no patches in make are necessary.

**Closed as completed by dmik** 2023-03-24 19:13 UTC
